# dvc project pipeline

# year 2017 inference only (disabled for now)
stages:
  createtiles:
    foreach:
    #  - 2017
      - 2019
    do:
      cmd: >-
        mkdir data/processed;
        gdal_retile.py 
        -csv locations.csv 
        -v -ps ${source_dim} ${source_dim}
        -co "TILED=YES" -co "COMPRESS=LZW" 
        -targetDir data/processed.images.${item} 
        data/raw/ortho_${item}_ESPG3044.tif
      deps:
      - data/raw/ortho_${item}_ESPG3044.tif
      params:
      - source_dim
      outs:
      - data/processed.images.${item}

  createmasks:
    cmd: >-
      python createmasks.py 
      --bbox data/raw/shapefiles/deadtrees_area/deadtrees_area.shp
      data/processed.images.2019 
      data/processed.masks.2019 
      data/raw/shapefiles/deadtrees/deadtrees.shp
    deps:
    - data/processed.images.2019
    - data/raw/shapefiles/deadtrees
    - data/raw/shapefiles/deadtrees_area
    outs:
    - data/processed.masks.2019

  createdataset:
    cmd: >-
      python createdataset.py data/processed.images.2019 data/processed.masks.2019 data/dataset 
      --source_dim ${source_dim}
      --tile_size ${createdataset.tile_size}
      --format ${file_type}
    deps:
    - data/processed.images.2019
    - data/processed.masks.2019 
    params:
    - source_dim
    - createdataset.tile_size
    - file_type
    outs:
    - data/dataset/train
    - data/dataset/stats.csv 

  createbalanced:
    cmd: >-
      python createbalanced.py 
      data/dataset/stats.csv
      data/dataset/train 
      data/dataset/train_balanced 
      data/dataset/train_balanced_short
      --format ${file_type}
      --tmp-dir ./tmp
    deps:
    - data/dataset/train
    - data/dataset/stats.csv
    params:
    - file_type
    outs:
    - data/dataset/train_balanced
    - data/dataset/train_balanced_short

  # train:
